#!/bin/bash

set -f

saveIFS=$IFS
IFS='=&'
parm=($QUERY_STRING)
declare -A PARAMS
for ((i=0; i<${#parm[@]}; i+=2))
do
	PARAMS[${parm[i]}]=$(echo "${parm[i+1]}" | grep -o "[a-zA-Z0-9_-]*" | head -1)
done
IFS=$saveIFS

if [[ -n "${PARAMS[type]}" ]]; then
  . "/var/lib/redeploy/lastdeploy-${PARAMS[type]}"
else
  RUN_LOG_FILE=/var/log/redeploy.log
fi

echo "Content-type: text/html; charset=utf-8"
echo

cat << EOF
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <style>
    	div {
	   margin: 0px 4px 4px 0px;
	}
    </style>
</head>
<body>
  <main class='container'>
    <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
      <div class="col-md-6 px-0">
        <h1 class="display-4 fst-italic">Showing log:</h1>
        <h3 class="fst-italic">${RUN_LOG_FILE}</h3>
        ${DATE_TIME}
      </div>
    </div>
    <div><a href="index">Back</a></div>
    <pre>
EOF
sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g; s/'"'"'/\&#39;/g' "${RUN_LOG_FILE}"
cat << EOF
    </pre>
  </main>
</body>
</html>
EOF
